import type { CardDefinition, EncounterDefinition } from './types';

export const CARDS: Record<string, CardDefinition> = {
  hammer: { id: 'hammer', name: 'Percussive Maintenance', cost: 1, type: 'attack', target: 'enemy', description: 'Deal 6 damage.\nOn critical hit: Ringing.', flavor: 'If it moves and it shouldn’t, hit it.', icon: 'hammer', effects: [{ kind: 'damage', amount: 6, recipient: 'target' }], onCritical: [{ kind: 'ringing', amount: 1, recipient: 'target' }], scaling: { effects: [4], description: 'Deal {effect:0} damage.\nOn critical hit: Ringing.' } },
  vest: { id: 'vest', name: 'Safety-ish Vest', cost: 1, type: 'skill', target: 'self', description: 'Gain 7 Block until your next action.', flavor: 'OSHA has left the chat.', icon: 'shield', effects: [{ kind: 'block', amount: 7, recipient: 'self' }], scaling: { effects: [3], description: 'Gain {effect:0} Block until your next action.' } },
  tape: { id: 'tape', name: 'Measure Once', cost: 1, type: 'skill', target: 'enemy', description: 'Apply 8 Exposed. The next hit deals 8 extra damage.', flavor: 'We are absolutely cutting twice.', icon: 'tape', effects: [{ kind: 'exposed', amount: 8, recipient: 'target' }], scaling: { effects: [2], description: 'Apply {effect:0} Exposed. The next hit deals {effect:0} extra damage.' } },
  heavy: { id: 'heavy', name: 'Warranty Voided', cost: 2, type: 'attack', target: 'enemy', description: 'Deal 13 damage.', flavor: 'Normal wear and tear. Probably.', icon: 'hammer', effects: [{ kind: 'damage', amount: 13, recipient: 'target' }], scaling: { effects: [4], description: 'Deal {effect:0} damage.' } },
  coffee: { id: 'coffee', name: 'Break Room Coffee', cost: 0, type: 'power', target: 'self', description: 'Gain 1 stored energy, up to your cap.', flavor: 'Brewed Tuesday. Which Tuesday?', icon: 'coffee', effects: [{ kind: 'energy', amount: 1, recipient: 'self' }], scaling: { effects: [1], description: 'Gain {effect:0} stored energy, up to your cap.' } },
  toolbox: { id: 'toolbox', name: 'Check the Toolbox', cost: 1, type: 'skill', target: 'self', description: 'Draw 2 extra cards.', flavor: 'It’s always in the other pocket.', icon: 'toolbox', effects: [{ kind: 'draw', amount: 2, recipient: 'self' }], scaling: { effects: [1], description: 'Draw {effect:0} extra cards.' } },
  brace: { id: 'brace', name: 'Steel-Toe Solution', cost: 1, type: 'attack', target: 'enemy', description: 'Deal 4 damage. Gain 3 Block until your next action.', flavor: 'The customer is no longer right.', icon: 'boot', effects: [{ kind: 'damage', amount: 4, recipient: 'target' }, { kind: 'block', amount: 3, recipient: 'self' }], scaling: { effects: [2, 2], description: 'Deal {effect:0} damage. Gain {effect:1} Block until your next action.' } },
  weaken: { id: 'weaken', name: 'Trip Hazard', cost: 1, type: 'skill', target: 'enemy', description: 'Downgrade an enemy’s next card 1 level.', flavor: 'Mind the freshly mopped floor.', icon: 'boot', effects: [], modifier: { levels: -1 } },
  reinforce: { id: 'reinforce', name: 'Duct Tape Upgrade', cost: 1, type: 'skill', target: 'self', description: 'Upgrade one hand card 1 level for its next play.', flavor: 'Load-bearing adhesive.', icon: 'tape', effects: [], modifier: { levels: 1 } },
  overtime: { id: 'overtime', name: 'Overtime Approved', cost: 1, type: 'power', target: 'self', description: 'Stretch for 4 ticks. Enemies need 2 ticks per action.', flavor: 'Just one more thing before you clock out.', icon: 'coffee', art: 'coffee', effects: [], time: { kind: 'stretch', amount: 4 }, scaling: { time: { amount: 1 }, description: 'Stretch for {time} ticks. Enemies need 2 ticks per action.' } },
  lookout: { id: 'lookout', name: 'Read the Fine Print', cost: 0, type: 'skill', target: 'self', description: 'Scouting: reveal 3 extra future ticks for 4 ticks.', flavor: 'The danger was in the small print.', icon: 'tape', art: 'tape', effects: [], time: { kind: 'scout', amount: 3 }, scaling: { time: { amount: 1 }, description: 'Scouting: reveal {time} extra future ticks for 4 ticks.' } },
  clockout: { id: 'clockout', name: 'Clock Out Early', cost: 1, type: 'power', target: 'self', description: 'Compress for 3 ticks. Enemies take 2 actions per tick.', flavor: 'That sounds like tomorrow’s problem.', icon: 'toolbox', art: 'toolbox', effects: [], time: { kind: 'compress', amount: 3 }, scaling: { time: { amount: 1 }, description: 'Compress for {time} ticks. Enemies take 2 actions per tick.' } },
  surge: { id: 'surge', name: 'Second Wind', cost: 0, type: 'power', target: 'self', description: 'Gain 2 Surge energy. Unused Surge expires after 4 ticks.', flavor: 'One last burst before clocking out.', icon: 'coffee', art: 'coffee', effects: [{ kind: 'energy', amount: 2, recipient: 'self' }], scaling: { effects: [2], description: 'Gain {effect:0} Surge energy. Unused Surge expires after 4 ticks.' }, surge: true },
  receipt: { id: 'receipt', name: 'Keep Your Receipt', cost: 1, type: 'skill', target: 'self', description: 'Retain one other hand card after its next play instead of replacing it.', flavor: 'Proof that you meant to do that.', icon: 'tape', art: 'time-retain', effects: [], temporal: { kind: 'retain' } },
  reclaim: { id: 'reclaim', name: 'Valid Receipt', cost: 0, type: 'skill', target: 'self', description: 'Rewind up to 8 ticks. Spend your checkpoint charge. Exhaust.', flavor: 'Original packaging not required.', icon: 'toolbox', art: 'time-reclaim', effects: [], time: { kind: 'rewind', amount: 8 } },
  borrow: { id: 'borrow', name: 'Advance Delivery', cost: 0, type: 'power', target: 'self', description: 'Borrow 2 extra cards. Skip the next 2 replacement draws. Exhaust.', flavor: 'Tomorrow called. It wants a tracking number.', icon: 'toolbox', art: 'time-borrow', effects: [], temporal: { kind: 'borrow', amount: 2 } },
  echo: { id: 'echo', name: 'That Bit Worked', cost: 2, type: 'attack', target: 'enemy', description: 'Echo a recent combat action. Once per original action.', flavor: 'Do the good bit again. Leave out the screaming.', icon: 'hammer', art: 'time-echo', effects: [], temporal: { kind: 'echo' } },
  secondcoat: { id: 'secondcoat', name: 'Second Coat', cost: 1, type: 'skill', target: 'self', description: 'Echo a recent defense. Once per original action.', flavor: 'The first coat is still drying yesterday.', icon: 'shield', art: 'time-second-coat', effects: [], temporal: { kind: 'echo', defenseOnly: true } },
  quickfix: { id: 'quickfix', name: 'Quick Fix', cost: 1, type: 'skill', target: 'self', description: 'Restore 4 health.', flavor: 'Structurally, that is probably skin.', icon: 'tape', art: 'tape', effects: [{ kind: 'heal', amount: 4, recipient: 'self' }], scaling: { effects: [2], description: 'Restore {effect:0} health.' } },
  doubletap: { id: 'doubletap', name: 'Two Gentle Taps', cost: 1, type: 'attack', target: 'enemy', description: 'Deal 3 damage twice. Exposed is consumed by the first hit.', flavor: 'Gentle is a warranty classification.', icon: 'hammer', art: 'hammer', effects: [{ kind: 'damage', amount: 3, recipient: 'target' }, { kind: 'damage', amount: 3, recipient: 'target' }], scaling: { effects: [2, 2], description: 'Deal {effect:0} damage, then {effect:1} damage. Exposed is consumed by the first hit.' } },
  crowbar: { id: 'crowbar', name: 'Open for Inspection', cost: 1, type: 'attack', target: 'enemy', description: 'Deal 4 damage. Then apply 3 Exposed.', flavor: 'An opening for a productive conversation.', icon: 'hammer', art: 'hammer', effects: [{ kind: 'damage', amount: 4, recipient: 'target' }, { kind: 'exposed', amount: 3, recipient: 'target' }], scaling: { effects: [2, 1], description: 'Deal {effect:0} damage. Then apply {effect:1} Exposed.' } },
  hardhat: { id: 'hardhat', name: 'Hard-Headed', cost: 0, type: 'skill', target: 'self', description: 'Gain 3 Block until your next action.', flavor: 'A thought bounced off it once.', icon: 'shield', art: 'vest', effects: [{ kind: 'block', amount: 3, recipient: 'self' }], scaling: { effects: [2], description: 'Gain {effect:0} Block until your next action.' } },
  barricade: { id: 'barricade', name: 'Aisle Closed', cost: 2, type: 'skill', target: 'self', description: 'Gain 14 Block until your next action.', flavor: 'Please shop around the active incident.', icon: 'shield', art: 'vest', effects: [{ kind: 'block', amount: 14, recipient: 'self' }], scaling: { effects: [5], description: 'Gain {effect:0} Block until your next action.' } },
  firstaid: { id: 'firstaid', name: 'First Aid-ish', cost: 2, type: 'skill', target: 'self', description: 'Gain 6 Block until your next action. Restore 5 health.', flavor: 'The kit contains a smaller roll of tape.', icon: 'toolbox', art: 'toolbox', effects: [{ kind: 'block', amount: 6, recipient: 'self' }, { kind: 'heal', amount: 5, recipient: 'self' }], scaling: { effects: [3, 2], description: 'Gain {effect:0} Block until your next action. Restore {effect:1} health.' } },
  finisher: { id: 'finisher', name: 'Job Satisfaction', cost: 2, type: 'attack', target: 'enemy', description: 'Deal 10 damage.\nOn critical hit: restore 6 health.', flavor: 'Finally, some positive feedback.', icon: 'hammer', art: 'heavy', effects: [{ kind: 'damage', amount: 10, recipient: 'target' }], onCritical: [{ kind: 'heal', amount: 6, recipient: 'self' }], scaling: { effects: [4], description: 'Deal {effect:0} damage.\nOn critical hit: restore 6 health.' } },
  precision: { id: 'precision', name: 'Pencil Mark', cost: 0, type: 'skill', target: 'enemy', description: 'Apply 3 Exposed. The next hit deals 3 extra damage.', flavor: 'Erasable. Technically.', icon: 'tape', art: 'tape', effects: [{ kind: 'exposed', amount: 3, recipient: 'target' }], scaling: { effects: [2], description: 'Apply {effect:0} Exposed. The next hit deals {effect:0} extra damage.' } },
  holdfast: { id: 'holdfast', name: 'Save It for Later', cost: 1, type: 'skill', target: 'self', description: 'Retain. Gain 5 Block until your next action.', flavor: 'The one useful thing in the other pocket.', icon: 'shield', art: 'vest', effects: [{ kind: 'block', amount: 5, recipient: 'self' }], retain: true, scaling: { effects: [3], description: 'Retain. Gain {effect:0} Block until your next action.' } },
  nightshift: { id: 'nightshift', name: 'Closing Argument', cost: 2, type: 'attack', target: 'enemy', description: 'Retain. Deal 11 damage.', flavor: 'He has been saving this all shift.', icon: 'hammer', art: 'heavy', effects: [{ kind: 'damage', amount: 11, recipient: 'target' }], retain: true, scaling: { effects: [4], description: 'Retain. Deal {effect:0} damage.' } },
  counterweight: { id: 'counterweight', name: 'Load-Bearing Boot', cost: 2, type: 'attack', target: 'enemy', description: 'Gain 8 Block until your next action. Deal 7 damage.', flavor: 'Stability through aggressive footwear.', icon: 'boot', art: 'brace', effects: [{ kind: 'block', amount: 8, recipient: 'self' }, { kind: 'damage', amount: 7, recipient: 'target' }], scaling: { effects: [3, 3], description: 'Gain {effect:0} Block until your next action. Deal {effect:1} damage.' } },
  'hammer-refined': { id: 'hammer-refined', name: 'Calibrated Maintenance', cost: 2, type: 'attack', target: 'enemy', description: 'Deal 12 damage.\nOn critical hit: Ringing.', flavor: 'Now with a precisely heavier handle.', icon: 'hammer', art: 'hammer', rarity: 'uncommon', effects: [{ kind: 'damage', amount: 12, recipient: 'target' }], onCritical: [{ kind: 'ringing', amount: 1, recipient: 'target' }], scaling: { effects: [4], description: 'Deal {effect:0} damage.\nOn critical hit: Ringing.' } },
  'vest-refined': { id: 'vest-refined', name: 'Load-Rated Vest', cost: 2, type: 'skill', target: 'self', description: 'Gain 16 Block until your next action.', flavor: 'Rated for one very specific emergency.', icon: 'shield', art: 'vest', rarity: 'uncommon', effects: [{ kind: 'block', amount: 16, recipient: 'self' }], scaling: { effects: [3], description: 'Gain {effect:0} Block until your next action.' } },
  'tape-refined': { id: 'tape-refined', name: 'Survey the Damage', cost: 2, type: 'skill', target: 'enemy', description: 'Apply 15 Exposed. The next hit deals 15 extra damage.', flavor: 'The diagram is now life-sized.', icon: 'tape', art: 'tape', rarity: 'uncommon', effects: [{ kind: 'exposed', amount: 15, recipient: 'target' }], scaling: { effects: [2], description: 'Apply {effect:0} Exposed. The next hit deals {effect:0} extra damage.' } },
};

// The opening hand exposes attacks, defense, timeline planning, and immediate Surge energy.
export const STARTER_DECK = ['hammer', 'vest', 'overtime', 'lookout', 'surge', 'weaken', 'reinforce', 'reinforce', 'weaken', 'tape', 'heavy', 'hammer', 'vest', 'brace', 'toolbox', 'hammer', 'vest', 'brace', 'clockout', 'coffee', 'surge'];
export const WORLD_RULES = { initialHand: 5, initialEnergy: 2, energyMax: 4, energyPerTick: 1, sight: 8, forecast: 6, rewindWindow: 8, potionHeal: 8, temporalDuration: 4 };
export const ENCOUNTER = { playerHp: 42, enemyHp: 48, initialHand: WORLD_RULES.initialHand, initialEnergy: WORLD_RULES.initialEnergy, energyMax: WORLD_RULES.energyMax, energyPerTick: WORLD_RULES.energyPerTick };

/** Permanent workshop conversions trade a higher energy price for a larger single action. */
export const REFINEMENTS: Record<string, string> = { hammer: 'hammer-refined', vest: 'vest-refined', tape: 'tape-refined' };

/** Authored repeating action sequences for the Last Customer expedition. */
export const ENCOUNTERS: Record<string, EncounterDefinition> = {
  security: { id: 'security', name: 'Possessed Security', title: 'The Entrance', description: 'One appointment at a time. Put protection before the impact.', hp: 38, actions: [
    { name: 'Receipt Check', description: 'Deal 6 damage.', effects: [{ kind: 'damage', amount: 6, recipient: 'target' }], scaling: { effects: [4], description: 'Deal {effect:0} damage.' } },
    { name: 'Marked for Review', description: 'Apply 2 Exposed.', effects: [{ kind: 'exposed', amount: 2, recipient: 'target' }], scaling: { effects: [1], description: 'Apply {effect:0} Exposed.' } },
    { name: 'Excessive Force', description: 'Deal 10 damage.', effects: [{ kind: 'damage', amount: 10, recipient: 'target' }], scaling: { effects: [4], description: 'Deal {effect:0} damage.' } },
    { name: 'First Aid Violation', description: 'Restore 4 health.', effects: [{ kind: 'heal', amount: 4, recipient: 'self' }], scaling: { effects: [2], description: 'Restore {effect:0} health.' } },
  ] },
  checkout: { id: 'checkout', name: 'Possessed Checkout Clerk', title: 'Express Checkout', description: 'A scan precedes the charge. A harmless appointment can still set up a dangerous one.', hp: 44, actions: [
    { name: 'Item Scanned', description: 'Apply 3 Exposed.', effects: [{ kind: 'exposed', amount: 3, recipient: 'target' }], scaling: { effects: [1], description: 'Apply {effect:0} Exposed.' } },
    { name: 'Unexpected Charge', description: 'Deal 7 damage.', effects: [{ kind: 'damage', amount: 7, recipient: 'target' }], scaling: { effects: [4], description: 'Deal {effect:0} damage.' } },
    { name: 'Service Charge', description: 'Deal 6 damage.', effects: [{ kind: 'damage', amount: 6, recipient: 'target' }], scaling: { effects: [4], description: 'Deal {effect:0} damage.' } },
  ] },
  stacker: { id: 'stacker', name: 'Possessed Shelf Stacker', title: 'Load-Bearing Shelves', description: 'Protection arrives before a heavy delivery. Attack before the shield or wait out its expiry.', hp: 46, actions: [
    { name: 'Pallet Wall', description: 'Gain 7 Block until your next action.', effects: [{ kind: 'block', amount: 7, recipient: 'self' }], scaling: { effects: [3], description: 'Gain {effect:0} Block until your next action.' } },
    { name: 'Heavy Delivery', description: 'Deal 8 damage.', effects: [{ kind: 'damage', amount: 8, recipient: 'target' }], scaling: { effects: [4], description: 'Deal {effect:0} damage.' } },
    { name: 'Falling Stock', description: 'Deal 7 damage.', effects: [{ kind: 'damage', amount: 7, recipient: 'target' }], scaling: { effects: [4], description: 'Deal {effect:0} damage.' } },
  ] },
  cleaner: { id: 'cleaner', name: 'Possessed Cleaner', title: 'Wet Floor', description: 'Alternating pressure and recovery rewards a planned burst, not endless waiting.', hp: 48, actions: [
    { name: 'Mind the Mop', description: 'Deal 8 damage.', effects: [{ kind: 'damage', amount: 8, recipient: 'target' }], scaling: { effects: [4], description: 'Deal {effect:0} damage.' } },
    { name: 'Fresh Coat', description: 'Gain 5 Block until your next action. Restore 3 health.', effects: [{ kind: 'block', amount: 5, recipient: 'self' }, { kind: 'heal', amount: 3, recipient: 'self' }], scaling: { effects: [3, 2], description: 'Gain {effect:0} Block until your next action. Restore {effect:1} health.' } },
    { name: 'Cautionary Impact', description: 'Deal 9 damage.', effects: [{ kind: 'damage', amount: 9, recipient: 'target' }], scaling: { effects: [4], description: 'Deal {effect:0} damage.' } },
  ] },
  greeter: { id: 'greeter', name: 'Possessed Greeter', title: 'Have a MORE Day', description: 'A mild welcome gives way to an advertised heavy hit. Keep an answer for later.', hp: 48, actions: [
    { name: 'Warm Welcome', description: 'Deal 3 damage.', effects: [{ kind: 'damage', amount: 3, recipient: 'target' }], scaling: { effects: [2], description: 'Deal {effect:0} damage.' } },
    { name: 'Helpful Directions', description: 'Apply 3 Exposed.', effects: [{ kind: 'exposed', amount: 3, recipient: 'target' }], scaling: { effects: [1], description: 'Apply {effect:0} Exposed.' } },
    { name: 'Mandatory Hospitality', description: 'Deal 14 damage.', effects: [{ kind: 'damage', amount: 14, recipient: 'target' }], scaling: { effects: [4], description: 'Deal {effect:0} damage.' } },
  ] },
  supervisor: { id: 'supervisor', name: 'Possessed Shift Supervisor', title: 'Performance Review', description: 'A denser sequence and Ringing demand fewer, more useful actions.', hp: 56, actions: [
    { name: 'Written Warning', description: 'Apply 2 Exposed.', effects: [{ kind: 'exposed', amount: 2, recipient: 'target' }], scaling: { effects: [1], description: 'Apply {effect:0} Exposed.' } },
    { name: 'Corrective Action', description: 'Deal 5 damage.', effects: [{ kind: 'damage', amount: 5, recipient: 'target' }], scaling: { effects: [3], description: 'Deal {effect:0} damage.' } },
    { name: 'Mandatory Briefing', description: 'Apply Ringing. The target skips its next action.', effects: [{ kind: 'ringing', amount: 1, recipient: 'target' }] },
    { name: 'Follow-Up Meeting', description: 'Deal 8 damage.', effects: [{ kind: 'damage', amount: 8, recipient: 'target' }], scaling: { effects: [4], description: 'Deal {effect:0} damage.' } },
  ] },
  'floor-manager': { id: 'floor-manager', name: 'Possessed Floor Manager', title: 'We Have Always Been Open', description: 'Optional elite: a dense protection-and-pressure sequence. The reward is an extra draft, not a mandatory toll.', hp: 62, boss: true, actions: [
    { name: 'Store Policy', description: 'Gain 5 Block until your next action.', effects: [{ kind: 'block', amount: 5, recipient: 'self' }], scaling: { effects: [3], description: 'Gain {effect:0} Block until your next action.' } },
    { name: 'Policy Enforcement', description: 'Deal 7 damage.', effects: [{ kind: 'damage', amount: 7, recipient: 'target' }], scaling: { effects: [4], description: 'Deal {effect:0} damage.' } },
    { name: 'Incident Report', description: 'Apply 2 Exposed.', effects: [{ kind: 'exposed', amount: 2, recipient: 'target' }], scaling: { effects: [1], description: 'Apply {effect:0} Exposed.' } },
    { name: 'Escalated Complaint', description: 'Deal 10 damage.', effects: [{ kind: 'damage', amount: 10, recipient: 'target' }], scaling: { effects: [4], description: 'Deal {effect:0} damage.' } },
  ] },
  'night-manager': { id: 'night-manager', name: 'Possessed Night Manager', title: 'Please Remain for Closing', description: 'The last host stands between the store and tomorrow. Break the repeating shift.', hp: 76, boss: true, actions: [
    { name: 'Closing Announcement', description: 'Deal 8 damage.', effects: [{ kind: 'damage', amount: 8, recipient: 'target' }], scaling: { effects: [4], description: 'Deal {effect:0} damage.' } },
    { name: 'Shutters Down', description: 'Gain 6 Block until your next action.', effects: [{ kind: 'block', amount: 6, recipient: 'self' }], scaling: { effects: [3], description: 'Gain {effect:0} Block until your next action.' } },
    { name: 'Tomorrow Cancelled', description: 'Apply 3 Exposed.', effects: [{ kind: 'exposed', amount: 3, recipient: 'target' }], scaling: { effects: [1], description: 'Apply {effect:0} Exposed.' } },
    { name: 'One More Tuesday', description: 'Deal 10 damage.', effects: [{ kind: 'damage', amount: 10, recipient: 'target' }], scaling: { effects: [4], description: 'Deal {effect:0} damage.' } },
  ] },
};

